# Generated by Django 6.0.7 on 2026-07-16 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistIdentity',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('did', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField()),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('medium', models.CharField(default='', max_length=255)),
                ('year_created', models.IntegerField(blank=True, null=True)),
                ('royalty_percentage_bps', models.IntegerField()),
                ('artist_wallet_address', models.CharField(max_length=42)),
                ('artist_did', models.CharField(default='', max_length=255)),
                ('image_ipfs_uri', models.CharField(default='', max_length=255)),
                ('metadata_ipfs_uri', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PINNED', 'Pinned'), ('MINTED', 'Minted')], default='UPLOADED', max_length=16)),
                ('created_at', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('token_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content_hash_hex', models.CharField(max_length=64)),
                ('contract_address', models.CharField(max_length=42)),
                ('tx_hash', models.CharField(max_length=255)),
                ('owner_address', models.CharField(max_length=42)),
                ('royalty_percentage_bps', models.IntegerField()),
                ('royalty_recipient', models.CharField(max_length=42)),
                ('minted_at', models.CharField(max_length=32)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='api.artwork')),
            ],
        ),
    ]
